[build]
builder = "NIXPACKS"
buildCommand = "dotnet restore && dotnet build -c Release"

[deploy]
startCommand = "dotnet run --project E-Com.API/E-Com.API.csproj --no-build --urls http://0.0.0.0:3000"


[variables]
DOTNET_VERSION = "8.0.100"